TOPICS = {
    0: "Fundamentals",
    1: "Blockchain Technology",
    2: "Cryptocurrency",
    3: "Decentralization",
    4: "Distributed Ledger Technology (DLT)",
    5: "Hashing",
    6: "Smart Contracts",
    7: "Consensus Mechanisms (Proof of Work, Proof of Stake)",
    8: "Nodes",
    9: "Mining",
    10: "Public and Private Keys",
    11: "Wallets (Hot vs. Cold Wallets)",
    12: "Transactions",
    13: "Blocks",
    14: "Block Rewards",
    15: "Gas Fees",
    16: "Non-Fungible Tokens (NFTs)",
    17: "Tokens (Utility vs. Security Tokens)",
    18: "Token Standards (ERC-20, ERC-721, ERC-1155)",
    19: "Forks (Hard Fork vs. Soft Fork)",
    20: "Blockchain Scalability (Layer 1 vs. Layer 2)",
    21: "Key Platforms & Protocols",
    22: "Bitcoin (BTC)",
    23: "Ethereum (ETH)",
    24: "Solana (SOL)",
    25: "Binance Smart Chain (BSC)",
    26: "Polygon (MATIC)",
    27: "Avalanche (AVAX)",
    28: "Polkadot (DOT)",
    29: "Cosmos (ATOM)",
    30: "Cardano (ADA)",
    31: "Tron (TRX)",
    32: "Decentralized Finance (DeFi)",
    33: "Decentralized Exchanges (DEXs)",
    34: "Automated Market Makers (AMMs)",
    35: "Liquidity Pools",
    36: "Yield Farming",
    37: "Staking",
    38: "Lending & Borrowing",
    39: "Stablecoins",
    40: "Impermanent Loss",
    41: "DeFi Protocols (Uniswap, Aave, Compound)",
    42: "Flash Loans",
    43: "Web3 Applications",
    44: "Web3 Browsers",
    45: "Decentralized Apps (dApps)",
    46: "Oracles (Chainlink, Band Protocol)",
    47: "Decentralized Identity",
    48: "IPFS (InterPlanetary File System)",
    49: "Metamask Wallet",
    50: "Web3 Social Media",
    51: "Decentralized Cloud Storage",
    52: "DAOs (Decentralized Autonomous Organizations)",
    53: "Play-to-Earn (P2E) Games",
    54: "Security & Privacy",
    55: "Cryptography",
    56: "Private vs. Public Blockchain",
    57: "Sybil Attacks",
    58: "51% Attacks",
    59: "Wallet Security (Seed Phrases)",
    60: "Multi-Signature Wallets",
    61: "Zero-Knowledge Proofs (ZKPs)",
    62: "Privacy Coins (Monero, Zcash)",
    63: "Encryption",
    64: "Rug Pulls and Scams",
    65: "Development Tools & Frameworks",
    66: "Solidity Programming",
    67: "Web3.js",
    68: "Ethers.js",
    69: "Truffle Suite",
    70: "Hardhat",
    71: "Smart Contract Testing",
    72: "Remix IDE",
    73: "The Graph",
    74: "Decentralized Storage Protocols (Filecoin, Arweave)",
    75: "Substrate Framework",
    76: "Ecosystem Trends",
    77: "Layer 2 Scaling Solutions (Arbitrum, Optimism)",
    78: "Cross-Chain Bridges",
    79: "Rollups (Optimistic Rollups, ZK Rollups)",
    80: "Tokenomics",
    81: "Governance Tokens",
    82: "Airdrops",
    83: "Meme Coins (Dogecoin, Shiba Inu)",
    84: "Wrapped Tokens (Wrapped Bitcoin - WBTC)",
    85: "Real-World Asset Tokenization",
    86: "Institutional Adoption",
    87: "Regulation & Compliance",
    88: "KYC (Know Your Customer) in Crypto",
    89: "AML (Anti-Money Laundering) Regulations",
    90: "Security Token Offerings (STOs)",
    91: "Initial Coin Offerings (ICOs)",
    92: "Initial DEX Offerings (IDOs)",
    93: "Regulatory Bodies (SEC, CFTC, FATF)",
    94: "Crypto Taxation",
    95: "Jurisdictional Differences (Crypto Laws Worldwide)",
    96: "Blockchain Transparency",
    97: "Compliance Tools (Chainalysis, Elliptic)",
    98: "Emerging Concepts",
    99: "Decentralized Science (DeSci)",
    100: "Soulbound Tokens (SBTs)",
    101: "Metaverse Integration",
    102: "AI and Blockchain",
    103: "Blockchain in Supply Chain",
    104: "Blockchain in Healthcare",
    105: "Decentralized Insurance",
    106: "Decentralized Governance Models",
    107: "Green Blockchain Initiatives",
    108: "Quantum-Resistant Cryptography"
}